// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $lst25_bestellzettel from "./routes/lst25/bestellzettel.tsx";
import * as $lst25_discord from "./routes/lst25/discord.tsx";
import * as $lst25_feedback from "./routes/lst25/feedback.tsx";
import * as $lst25_haftungsausschluss from "./routes/lst25/haftungsausschluss.tsx";
import * as $lst25_helferprotokoll from "./routes/lst25/helferprotokoll.tsx";
import * as $lst25_index from "./routes/lst25/index.tsx";
import * as $lst25_naechstesJahr from "./routes/lst25/naechstesJahr.tsx";
import * as $lst25_namenstafeln from "./routes/lst25/namenstafeln.tsx";
import * as $lst25_preisliste from "./routes/lst25/preisliste.tsx";
import * as $lst25_programm from "./routes/lst25/programm.tsx";
import * as $lst25_rollenspieltage from "./routes/lst25/rollenspieltage.tsx";
import * as $lst25_wc from "./routes/lst25/wc.tsx";
import * as $lst25_wegweiser from "./routes/lst25/wegweiser.tsx";
import * as $lst25_willkommen from "./routes/lst25/willkommen.tsx";
import * as $rst24_bestellzettel from "./routes/rst24/bestellzettel.tsx";
import * as $rst24_discord from "./routes/rst24/discord.tsx";
import * as $rst24_feedback from "./routes/rst24/feedback.tsx";
import * as $rst24_index from "./routes/rst24/index.tsx";
import * as $rst24_naechstesJahr from "./routes/rst24/naechstesJahr.tsx";
import * as $rst24_preisliste from "./routes/rst24/preisliste.tsx";
import * as $rst24_programm from "./routes/rst24/programm.tsx";
import * as $rst24_wc from "./routes/rst24/wc.tsx";
import * as $rst24_willkommen from "./routes/rst24/willkommen.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/lst25/bestellzettel.tsx": $lst25_bestellzettel,
    "./routes/lst25/discord.tsx": $lst25_discord,
    "./routes/lst25/feedback.tsx": $lst25_feedback,
    "./routes/lst25/haftungsausschluss.tsx": $lst25_haftungsausschluss,
    "./routes/lst25/helferprotokoll.tsx": $lst25_helferprotokoll,
    "./routes/lst25/index.tsx": $lst25_index,
    "./routes/lst25/naechstesJahr.tsx": $lst25_naechstesJahr,
    "./routes/lst25/namenstafeln.tsx": $lst25_namenstafeln,
    "./routes/lst25/preisliste.tsx": $lst25_preisliste,
    "./routes/lst25/programm.tsx": $lst25_programm,
    "./routes/lst25/rollenspieltage.tsx": $lst25_rollenspieltage,
    "./routes/lst25/wc.tsx": $lst25_wc,
    "./routes/lst25/wegweiser.tsx": $lst25_wegweiser,
    "./routes/lst25/willkommen.tsx": $lst25_willkommen,
    "./routes/rst24/bestellzettel.tsx": $rst24_bestellzettel,
    "./routes/rst24/discord.tsx": $rst24_discord,
    "./routes/rst24/feedback.tsx": $rst24_feedback,
    "./routes/rst24/index.tsx": $rst24_index,
    "./routes/rst24/naechstesJahr.tsx": $rst24_naechstesJahr,
    "./routes/rst24/preisliste.tsx": $rst24_preisliste,
    "./routes/rst24/programm.tsx": $rst24_programm,
    "./routes/rst24/wc.tsx": $rst24_wc,
    "./routes/rst24/willkommen.tsx": $rst24_willkommen,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
