// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $bestellzettel from "./routes/bestellzettel.tsx";
import * as $feedback from "./routes/feedback.tsx";
import * as $naechstesJahr from "./routes/naechstesJahr.tsx";
import * as $preisliste from "./routes/preisliste.tsx";
import * as $programm from "./routes/programm.tsx";
import * as $willkommen from "./routes/willkommen.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/bestellzettel.tsx": $bestellzettel,
    "./routes/feedback.tsx": $feedback,
    "./routes/naechstesJahr.tsx": $naechstesJahr,
    "./routes/preisliste.tsx": $preisliste,
    "./routes/programm.tsx": $programm,
    "./routes/willkommen.tsx": $willkommen,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
